// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PH44331_SD20103_Assignment_CSharp6.Models;

[Table("Account")]
[Index("AccUsername", Name = "UQ__Account__136121E1D7533B62", IsUnique = true)]
public partial class Account
{
    [Key]
    [Column("ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [Column("acc_username")]
    [StringLength(50)]
    public string AccUsername { get; set; }

    [Required]
    [Column("acc_password")]
    [StringLength(50)]
    public string AccPassword { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BirthDate { get; set; }

    [Column("acc_role")]
    [StringLength(10)]
    [Unicode(false)]
    public string AccRole { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<Receipt> Receipts { get; set; } = new List<Receipt>();
}