// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PH44331_SD20103_Assignment_CSharp6.Models;

public partial class FoodDBContext : DbContext
{
    public FoodDBContext(DbContextOptions<FoodDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Food> Foods { get; set; }

    public virtual DbSet<Receipt> Receipts { get; set; }

    public virtual DbSet<ReceiptDetail> ReceiptDetails { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer("local");
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Account__3214EC2706947823");

            entity.Property(e => e.Id).IsFixedLength();
            entity.Property(e => e.AccRole).IsFixedLength();
        });

        modelBuilder.Entity<Food>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Food__3214EC2722135888");

            entity.Property(e => e.Id).IsFixedLength();
        });

        modelBuilder.Entity<Receipt>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Receipt__3214EC272D14BCAB");

            entity.Property(e => e.Id).IsFixedLength();
            entity.Property(e => e.AccountId).IsFixedLength();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Account).WithMany(p => p.Receipts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Receipt__Account__3D5E1FD2");
        });

        modelBuilder.Entity<ReceiptDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReceiptD__3214EC27243B65C8");

            entity.Property(e => e.Id).IsFixedLength();
            entity.Property(e => e.FoodId).IsFixedLength();
            entity.Property(e => e.ReceiptId).IsFixedLength();

            entity.HasOne(d => d.Food).WithMany(p => p.ReceiptDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ReceiptDe__Food___4222D4EF");

            entity.HasOne(d => d.Receipt).WithMany(p => p.ReceiptDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ReceiptDe__Recei__412EB0B6");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}