// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PH44331_SD20103_Assignment_CSharp6.Models;

[Table("Food")]
[Index("FoodName", Name = "UQ__Food__BB07E556FD4206AF", IsUnique = true)]
public partial class Food
{
    [Key]
    [Column("ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Id { get; set; }

    [Column("Food_Name")]
    [StringLength(50)]
    public string FoodName { get; set; }

    public bool? Available { get; set; }

    public int? Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal? Cost { get; set; }

    [Column("Image_Link")]
    [StringLength(500)]
    public string ImageLink { get; set; }

    [InverseProperty("Food")]
    public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; } = new List<ReceiptDetail>();
}