// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PH44331_SD20103_Assignment_CSharp6.Models;

[Table("ReceiptDetail")]
public partial class ReceiptDetail
{
    [Key]
    [Column("ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [Column("Receipt_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string ReceiptId { get; set; }

    [Required]
    [Column("Food_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string FoodId { get; set; }

    public int? Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal? TotalCost { get; set; }

    [ForeignKey("FoodId")]
    [InverseProperty("ReceiptDetails")]
    public virtual Food Food { get; set; }

    [ForeignKey("ReceiptId")]
    [InverseProperty("ReceiptDetails")]
    public virtual Receipt Receipt { get; set; }
}