// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PH44331_SD20103_Assignment_CSharp6.Models;

[Table("Receipt")]
public partial class Receipt
{
    [Key]
    [Column("ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [Column("Account_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string AccountId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Receipts")]
    public virtual Account Account { get; set; }

    [InverseProperty("Receipt")]
    public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; } = new List<ReceiptDetail>();
}